module.exports = {
    splashBg: require("../assets/images/splashBg.png"),
    appLogo: require("../assets/images/logo.png"),
    loginHeader: require("../assets/images/loginHeader.png"),
    lock: require("../assets/images/lock.png"),
    bell: require("../assets/images/bell.png"),
    fbIcon: require("../assets/images/fbIcon.png"),
    googleIcon: require("../assets/images/googleIcon.png"),
    user: require("../assets/images/user.png"),
    home: require("../assets/images/home.png"),
    profile: require("../assets/images/profile.png"),
    blackjack: require("../assets/images/blackjack.png"),
    activeGame: require("../assets/images/activeGame.png"),
    homeGrid1: require("../assets/images/home_grid_1.png"),
    homeGrid2: require("../assets/images/home_grid_2.png"),
    homeGrid3: require("../assets/images/home_grid_3.png"),
    menuIcon: require("../assets/images/menu-icon.png"),
    backArrow: require("../assets/images/back_arrow.png"),
    notification: require("../assets/images/notification.png"),
    notificationO: require("../assets/images/notification_o.png"),

    invite: require("../assets/images/menu/invite.png"),
    helpIcon: require("../assets/images/menu/help.png"),
    activityIcon: require("../assets/images/menu/activityIcon.png"),
    cardIcon: require("../assets/images/menu/cardIcon.png"),
    clockIcon: require("../assets/images/menu/clockIcon.png"),
    contactIcon: require("../assets/images/menu/contactIcon.png"),
    gamesIcon: require("../assets/images/menu/gamesIcon.png"),
    settingsIcon: require("../assets/images/menu/settingsIcon.png"),
    shareIcon: require("../assets/images/menu/shareIcon.png"),
    shareSocreIcon: require("../assets/images/shareIcon.png"),


    demo: require("../assets/images/demo/demo.png"),
    userImage: require("../assets/images/demo/user.png"),


    noImage: require("../assets/images/no-image.png"),
    coinYellow: require("../assets/images/coin_yellow.png"),
    FilterIcon: require("../assets/images/FilterIcon.png"),
    bottomBorder: require("../assets/images/bottomBorder.png"),
    hrIcon: require("../assets/images/hrIcon.png"),
    checkActive: require("../assets/images/check_active.png"),
    checkInactive: require("../assets/images/check_inactive.png"),
    championIcon: require("../assets/images/championIcon.png"),
    loserIcon: require("../assets/images/loserIcon.png"),
    quitsIcon: require("../assets/images/quitsIcon.png"),
    currancyIcon: require("../assets/images/currancyIcon.png"),
    sendCoin: require("../assets/images/sendCoin.png"),
    rsGreen: require("../assets/images/rs_green.png"),
    redSmallArrow: require("../assets/images/red_small_arrow.png"),
    line: require("../assets/images/line.png"),
    verticalLine: require("../assets/images/verticalLine.png"),
    bankerIcon: require("../assets/images/bankerIcon.png"),
    RectangleBg: require("../assets/images/RectangleBg.png"),
    editIcon: require("../assets/images/editIcon.png"),
    assignIcon: require("../assets/images/assignIcon.png"),
    plusIcon: require("../assets/images/plusIcon.png"),
    crossIcon: require("../assets/images/crossIcon.png"),
    arrowGreen: require("../assets/images/arrowGreen.png"),
    arrowRed: require("../assets/images/arrowRed.png"),
    receiptIcon: require("../assets/images/receiptIcon.png"),
    paymentIcon: require("../assets/images/paymentIcon.png"),
    treeView: require("../assets/images/treeView.png"),
    footerImage: require("../assets/images/footer.png"),
    search: require("../assets/images/search.png"),
    locationblank: require("../assets/images/locationblank.png"),
    redSmallArrow: require("../assets/images/red_small_arrow.png"),
    arrow: require("../assets/images/arrow.png"),
    back: require("../assets/images/back.png"),
    arrowUpLeftIcon: require("../assets/images/arrowUpLeftIcon.png"),
    dateRangeIcon: require("../assets/images/dateRangeIcon.png"),
    imageIcon: require("../assets/images/imageIcon.png"),
    locationOnIcon: require("../assets/images/locationOnIcon.png"),
    noteAddIcon: require("../assets/images/noteAddIcon.png"),
    optionsIcon: require("../assets/images/optionsIcon.png"),
    searchIcon: require("../assets/images/searchIcon.png"),
    subtitlesIcon: require("../assets/images/subtitlesIcon.png"),

    loginBG: require("../assets/images/loginBG.png"),

    phoneIcon: require("../assets/images/phoneIcon.png"),
    groupIcon: require("../assets/images/groupIcon.png"),
    caretDownIcon: require("../assets/images/caret-down-icon.png"),
    activeCheck: require("../assets/images/active_check.png"),
    checked: require("../assets/images/checked.png"),
    unchecked: require("../assets/images/unchecked.png"),
    deleteIcon: require("../assets/images/delete-icon.png"),
    camera: require("../assets/images/camera.png"),
    gallery: require("../assets/images/gallery.png"),

    forgotPassword: require("../assets/images/forgot-password.png"),
    forgotPassword2: require("../assets/images/forgot-password-2.png"),

    logo: require("../assets/images/icon.png"),
    addPlayer: require("../assets/images/addPlayer.png"),
    
    triangle_Confirmed: require("../assets/images/triangle_Confirmed.png"),
    triangle_Pending: require("../assets/images/triangle_Pending.png"),
    triangle_Waiting: require("../assets/images/triangle_Waiting.png"),
    hrDate: require("../assets/images/hrDate.png"),
    arrowSquare: require("../assets/images/arrowSquare.png"),

    invitationIcon: require("../assets/images/invitationIcon.png"),
    twoUser: require("../assets/images/twoUser.png"),
    cancelEye: require("../assets/images/cancelEye.png"),
    calander: require("../assets/images/calander.png"),
    gear: require("../assets/images/gear.png"),

    coindown: require("../assets/images/coindown.png"),
    coinup: require("../assets/images/coinup.png"),
    coinstate: require("../assets/images/coinstate.png"),

    all_player: require("../assets/images/all_player.png"),
    loosplayer: require("../assets/images/loosplayer.png"),
    playercoin: require("../assets/images/playercoin.png"),
    winplayer: require("../assets/images/winplayer.png"),
    quits_player: require("../assets/images/quits_player.png"),

    google_play: require("../assets/images/google_play.png"),
    iphone: require("../assets/images/iphone.png"),
    android_logo: require("../assets/images/android_logo.png"),
    iphone_logo: require("../assets/images/iphone_logo.png"),


    left_arrow: require("../assets/images/icon/left-arrow.png"),
    right_arrow: require("../assets/images/icon/right-arrow.png"),

    card: require("../assets/images/card.png"),
  unselected_card: require("../assets/images/unselected_card.png"),
  card_2c: require("../assets/images/2c.png"),
  card_3c: require("../assets/images/3c.png"),
  card_4c: require("../assets/images/4c.png"),
  card_5c: require("../assets/images/5c.png"),
  card_6c: require("../assets/images/6c.png"),
  card_7c: require("../assets/images/7c.png"),
  card_8c: require("../assets/images/8c.png"),
  card_9c: require("../assets/images/9c.png"),
  card_Ac: require("../assets/images/Ac.png"),
  card_Jc: require("../assets/images/Jc.png"),
  card_Kc: require("../assets/images/Kc.png"),
  card_Qc: require("../assets/images/Qc.png"),
  card_Tc: require("../assets/images/Tc.png"),
  card_2d: require("../assets/images/2d.png"),
  card_3d: require("../assets/images/3d.png"),
  card_4d: require("../assets/images/4d.png"),
  card_5d: require("../assets/images/5d.png"),
  card_6d: require("../assets/images/6d.png"),
  card_7d: require("../assets/images/7d.png"),
  card_8d: require("../assets/images/8d.png"),
  card_9d: require("../assets/images/9d.png"),
  card_Ad: require("../assets/images/Ad.png"),
  card_Jd: require("../assets/images/Jd.png"),
  card_Kd: require("../assets/images/Kd.png"),
  card_Qd: require("../assets/images/Qd.png"),
  card_Td: require("../assets/images/Td.png"),
  card_2h: require("../assets/images/2h.png"),
  card_3h: require("../assets/images/3h.png"),
  card_4h: require("../assets/images/4h.png"),
  card_5h: require("../assets/images/5h.png"),
  card_6h: require("../assets/images/6h.png"),
  card_7h: require("../assets/images/7h.png"),
  card_8h: require("../assets/images/8h.png"),
  card_9h: require("../assets/images/9h.png"),
  card_Ah: require("../assets/images/Ah.png"),
  card_Jh: require("../assets/images/Jh.png"),
  card_Kh: require("../assets/images/Kh.png"),
  card_Qh: require("../assets/images/Qh.png"),
  card_Th: require("../assets/images/Th.png"),
  card_2s: require("../assets/images/2s.png"),
  card_3s: require("../assets/images/3s.png"),
  card_4s: require("../assets/images/4s.png"),
  card_5s: require("../assets/images/5s.png"),
  card_6s: require("../assets/images/6s.png"),
  card_7s: require("../assets/images/7s.png"),
  card_8s: require("../assets/images/8s.png"),
  card_9s: require("../assets/images/9s.png"),
  card_As: require("../assets/images/As.png"),
  card_Js: require("../assets/images/Js.png"),
  card_Ks: require("../assets/images/Ks.png"),
  card_Qs: require("../assets/images/Qs.png"),
  card_Ts: require("../assets/images/Ts.png"),
    
  indianRupee: require("../assets/images/currancy/rupees.png"),
  dollar: require("../assets/images/currancy/doller.png"),
  bhat: require("../assets/images/currancy/bhat.png"),
  pound: require("../assets/images/currancy/pound.png"),
  yen: require("../assets/images/currancy/yen.png"),
  euro: require("../assets/images/currancy/euro.png")
  
};  